# Generated by Django 5.1.3 on 2024-12-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author',
            new_name='author_id',
        ),
    ]
