# Generated by Django 5.1.3 on 2024-12-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_rename_author_feedback_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='author_id',
            new_name='author',
        ),
    ]
